"""empty message

Revision ID: 771f3b561dd7
Revises: 0b29e1b3767d
Create Date: 2018-10-15 11:17:04.461923

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '771f3b561dd7'
down_revision = '0b29e1b3767d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'jokes', ['contents'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'jokes', type_='unique')
    # ### end Alembic commands ###
